# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

#r: bioc-release
sudo: false


addons:
    apt:
      update: true

after_success:
  - Rscript -e 'library(covr);codecov()'
